const CONSTANTS = {
    SIGNUP: 'SIGNUP',
    LOGIN: 'LOGIN',
    CREATE_PRODUCT: 'CREATE_PRODUCT',
    GET_PRODUCT: 'GET_PRODUCT',
    LIST_PRODUCTS: 'LIST_PRODUCTS',
    CREATE_OPTIONS: 'CREATE_OPTIONS',
    PRICE_OPTIONS: 'PRICE_OPTIONS',
};

export default CONSTANTS
